spring.application.name=DRIVER-SERVICE

server.port=8085
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url =  jdbc:postgresql://localhost:5432/driver_db
spring.datasource.username = postgres
spring.datasource.password = 2736


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=kindconnect-secret-key-12345678901234567890
jwt.expiration=86400000

donation.service.url=http://localhost:8083

# ===============================
# Eureka Client Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# (Optional but good practice)
eureka.instance.prefer-ip-address=true