spring.application.name=API-GATEWAY
server.port=8765

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# Enable discovery (keep it ON for now)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#For Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

#For Donation Service
spring.cloud.gateway.routes[1].id=donation-service
spring.cloud.gateway.routes[1].uri=lb://DONATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/donations/**

#For Driver Service
spring.cloud.gateway.routes[2].id=driver-service
spring.cloud.gateway.routes[2].uri=lb://DRIVER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/driver/**

#For Ngo Service
spring.cloud.gateway.routes[3].id=ngo-service
spring.cloud.gateway.routes[3].uri=lb://NGO-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/ngo/**

#For Profile Service
spring.cloud.gateway.routes[4].id=profile-service
spring.cloud.gateway.routes[4].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/profiles/**