spring.application.name=service-registry-eureka

server.port=8761

# Eureka server does NOT register itself
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false