spring.application.name=AUTH-SERVICE

server.port = 8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url =  jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username = postgres
spring.datasource.password = 775161


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=kindconnect-secret-key-12345678901234567890
jwt.expiration=86400000

# ===============================
# OTP Configuration
# ===============================
otp.expiration.minutes=5
otp.length=6

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yagnikpansheriya7761@gmail.com
spring.mail.password=dppepwnbnbuyatuc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# ===============================
# Eureka Client Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# (Optional but good practice)
eureka.instance.prefer-ip-address=true
